name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        BUILD_TYPE: ["Debug"] # There is not cpp code so 1 build type is enough.
        os: [ windows-latest ]
    steps:

    - uses: actions/checkout@v5

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Get MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Show cmake version
      run: cmake --version

    - name: check sf exist
      run: |
        Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Service Fabric\' -Name FabricVersion
      shell: pwsh

    - name: run cmake
      run: > 
        cmake . -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -B build -T host=x64 -A x64
    - name: clean build
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target force_clean

    - name: run generate all
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target generate_winmd

    - name: validate winmd
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target validate_winmd