name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        BUILD_TYPE: ["Debug"] # There is not cpp code so 1 build type is enough.
        os: [ windows-latest ]
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

    - name: Get MSVC
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

    - name: Show cmake version
      run: cmake --version

    - name: check sf exist
      run: |
        Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Service Fabric\' -Name FabricVersion
      shell: pwsh

    - name: run cmake
      run: > 
        cmake . -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -B build -T host=x64 -A x64
    - name: clean build
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target force_clean

    - name: run generate all
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target generate_winmd

    - name: test metadata tooling
      run: cargo test --manifest-path rust-metadata\Cargo.toml --locked

    - name: validate winmd
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} --target validate_winmd